language: python
sudo: false

python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pytest pytest-cov

script:
  - export PYTHONPATH=$PYTHONPATH:.
  - py.test tests --cov coupang --durations=10

after_success:
  - coveralls
